language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - git clone https://github.com/openplanets/scape-platform-datamodel.git
  - cd scape-platform-datamodel
  - echo "Building scape-platform-datamodel revision:"
  - git rev-parse HEAD
  - mvn -q install
  - cd ..